### ISSUE TITLE
Deploy to VMAT2

### ISSUE THREAD

**Issue by natem345** [tiger12506/VMAT#80]
Deploy latest code from master to VMAT2
Directions here. Please update/clarify as needed for Brian: https://github.com/tiger12506/VMAT/wiki/Deployment-Guide

**Comment by CalMlynarczyk** [comment]
I believe this has already been taken care of. Surely future builds will get deployed as needed. I [committed a publishing profile](https://github.com/tiger12506/VMAT/commit/aabef85018b8f315e0f971a0f5548f583825b56d#diff-1) for everyone to use in the future so that we do not have to rely on only one person knowing how to publish to VMAT2. Most of the issues in the [Deployment Guide](https://github.com/tiger12506/VMAT/wiki/Deployment-Guide) are already resolved on VMAT2.
